const Stages = {
  '0': 'USER_ADDING_HEART_RATE_DATA',
  '1': 'NODES_ADDING_RESULT_COMMITMENTS',
  '2': 'NODES_ADDING_RESULT_REVEALS',
  '3': 'DISSENTING_PERIOD',
  '4': 'DISSENTS_NODES_ADDING_RESULT_COMMITMENTS',
  '5': 'DISSENTS_NODES_ADDING_RESULT_REVEALS',
  '6': 'SLASHING_PERIOD',
}

module.exports = Stages
