#!/bin/sh

CONTROLLER_PUBLIC_KEY=$1
CONTROLLER_PRIVATE_KEY=$2
TIME_PER_STAGE=$3
USER_COUNT=$4
NODE_COUNT=$5

CONTROLLER_LOG_FILE=logs/controllerNode.log
NODE_LOG_FILES=()

FIRST_NODE_INDEX=1

for (( i=$FIRST_NODE_INDEX; i<=$NODE_COUNT; i++ ))
do
    ((NODE_INDEX=i-1))
	NODE_LOG_FILES+=("logs/node${NODE_INDEX}.log") 
done
rm logs/*

CONTROLLER_PUBLIC_KEY=$CONTROLLER_PUBLIC_KEY CONTROLLER_PRIVATE_KEY=$CONTROLLER_PRIVATE_KEY node ../controllerNode/setupProxyForNewRound.js
CONTROLLER_PUBLIC_KEY=$CONTROLLER_PUBLIC_KEY CONTROLLER_PRIVATE_KEY=$CONTROLLER_PRIVATE_KEY TIME_PER_STAGE=$TIME_PER_STAGE node ../controllerNode >> $CONTROLLER_LOG_FILE &

for ((index=0; index<${#NODE_LOG_FILES[@]}; ++index)); do
    NODE_INDEX=$index TIME_PER_STAGE=$TIME_PER_STAGE USER_COUNT=$USER_COUNT node ../juriNode/ >> "${NODE_LOG_FILES[index]}" &
done

tail -f "${NODE_LOG_FILES[0]}"